Try the code block and execute catch when err is thrown
try {
Block of code to try
}
catch(err) {
Block of code to handle errors
}